### ISSUE TITLE
Unable to start Pattern Library on Terminal

### ISSUE THREAD

**Issue by AspirationYC** [AspirationYC/portfolio#1]
Hi @thomasjbradley

For some reason, I can't run my pattern library on Terminal and I can't solve it.
Screenshot: 
<img width="355" alt="Screen Shot 2019-10-01 at 2 14 40 PM" src="https://user-images.githubusercontent.com/31771017/65988742-638cc100-e456-11e9-8ff0-e32339f7f596.png">

Yu-Han Chang

**Comment by thomasjbradley** [comment]
On this line of code:
https://github.com/AspirationYC/portfolio/blob/master/Gemfile#L10

Remove this part:
```rb
, :path => '/www/jekyll_patternbot/'
```

**Comment by AspirationYC** [comment]
Thanks!
